FROM node:16

RUN mkdir /app
WORKDIR /app

COPY . /app

RUN npm ci
RUN npm install -g --unsafe-perm prisma
RUN npx prisma generate
RUN npx prisma migrate deploy

EXPOSE 3333

CMD [ "npm", "run", "start" ]