version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    networks:
      - ndi
    environment:
      TZ: Europe/Paris
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '127.0.0.1:${API_PORT}:3333'
    depends_on:
      - postgres
    environment:
      TZ: Europe/Paris
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
      API_PORT: '${API_PORT}'
    networks:
      - ndi
    restart: unless-stopped
networks:
  ndi:
